version: "3"
services:
  nginx:
    image: nginx:latest
    ports:
    - "80:80"
    volumes:
    - ./app:/app
    - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
  php:
    build: ./docker/php
    volumes:
    - ./app:/app
  db:
    image: percona:5.6
    environment:
    - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    - MYSQL_DATABASE=assessment
    volumes:
    - ./test-sql:/docker-entrypoint-initdb.d
    ports:
    - "3306:3306"
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - 8080:80
    links:
      - db
    environment:
      PMA_HOST: db
